AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda 関数・IAM ロール・S3 バケットを作成するスタック

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  MySampleBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled

  MyFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "my-func-${Env}"
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: src/lambda/
      Role: !GetAtt MyFunctionRole.Arn
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  FunctionUrl:
    Description: Lambda Function URL
    Value: !GetAtt MyFunctionUrl.FunctionUrl
