AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda 実行用 IAM マネージドポリシー

Resources:
  LambdaExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: my-lambda-execution-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*

Outputs:
  PolicyArn:
    Description: Lambda 実行用マネージドポリシーの ARN
    Value: !Ref LambdaExecutionPolicy
