AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda 関数・IAM ロール・S3 バケットを作成するスタック

Parameters:
  TemplateBucketName:
    Type: String
    Description: ネストスタックのテンプレート(iam-policy.yaml)を格納する S3 バケット名

Resources:
  S3:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: my-sample-bucket
      VersioningConfiguration:
        Status: Enabled

  IamPolicyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.amazonaws.com/templates/iam-policy.yaml"

  MylambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: my-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !GetAtt IamPolicyStack.Outputs.PolicyArn

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-func
      Role: !GetAtt MylambdaRole.Arn
      Handler: index.handler
      Runtime: nodejs22.x
      Code:
        S3Bucket: !Ref S3
        S3Key: lambda/my-func.zip
